CREATE TABLE EMP
(EMPNO INT,
ENAME VARCHAR(25),
JOB VARCHAR(12),
SALARY INT,
COMMISSION INT,
DEPTNO INT);

DESCRIBE EMP;

INSERT INTO EMP(EMPNO,ENAME,JOB,SALARY,DEPTNO)VALUES(7369,'SMITH','CLERK',800,20);
SELECT * FROM EMP ORDER BY EMPNO;

INSERT INTO EMP(EMPNO,ENAME,JOB,SALARY,COMMISSION,DEPTNO)VALUES(7499,'ALLEN','SALESMAN',1600,300,30),(7521,'WARD','SALESMAN',1250,500,30),(7654,'MARTIN','SALESMAN',1250,1400,30);
INSERT INTO EMP(EMPNO,ENAME,JOB,SALARY,DEPTNO)VALUES(7566,'JONES','MANAGER',2975,20),
(7698,'BLAKE','MANAGER',2850,30),(7782,'CLARK','MANAGER',2450,10),(7788,'SCOTT','ANALYST',3000,20),
(7839,'KING','PRESIDENT',5000,10),(7844,'TURNER','SALESMAN',1500,30),(7876,'ADAMS','CLERK',1100,20),
(7900,'JAMES','NULL',950,30),(7902,'FORD','ANALYST',3000,20),(7934,'MILLER','CLERK',1300,10);

UPDATE EMP SET JOB='CLERK' WHERE JOB='NULL';

ALTER TABLE EMP ADD DATE_JOIN VARCHAR(50);
DESCRIBE EMP;
UPDATE EMP SET DATE_JOIN='17-DEC-80' WHERE EMPNO=7369;
UPDATE EMP SET DATE_JOIN='20-FEB-81' WHERE EMPNO=7499;
UPDATE EMP SET DATE_JOIN='22-FEB-81' WHERE EMPNO=7521;
UPDATE EMP SET DATE_JOIN='02-APR-81' WHERE EMPNO=7566;
UPDATE EMP SET DATE_JOIN='28-SEP-81' WHERE EMPNO=7654;
UPDATE EMP SET DATE_JOIN='01-MAY-81' WHERE EMPNO=7698;
UPDATE EMP SET DATE_JOIN='09-JUN-81' WHERE EMPNO=7782;
UPDATE EMP SET DATE_JOIN='19-APR-87' WHERE EMPNO=7788;
UPDATE EMP SET DATE_JOIN='17-NOV-81' WHERE EMPNO=7839;
UPDATE EMP SET DATE_JOIN='08-SEP-81' WHERE EMPNO=7844;
UPDATE EMP SET DATE_JOIN='23-MAY-87' WHERE EMPNO=7876;
UPDATE EMP SET DATE_JOIN='03-DEC-81' WHERE EMPNO=7900;
UPDATE EMP SET DATE_JOIN='03-DEC-81' WHERE EMPNO=7902;
UPDATE EMP SET DATE_JOIN='23-JAN-82' WHERE EMPNO=7934;

SELECT * FROM EMP ORDER BY EMPNO;

SELECT DISTINCT JOB FROM EMP;

SELECT ENAME FROM EMP WHERE DEPTNO IN(20,30);

SELECT ENAME,SALARY+IFNULL(COMMISSION,0) AS Total_of_salary FROM EMP;

SELECT ENAME,SALARY*12 AS Annual_Salary  FROM EMP;

SELECT ENAME FROM EMP WHERE DATE_JOIN='03-DEC-81';

SELECT ENAME,SALARY+IFNULL(COMMISSION,0) AS Total_of_salary FROM EMP WHERE ENAME='MILLER';

DELETE FROM EMP WHERE ENAME='MILLER';
SELECT * FROM EMP ORDER BY EMPNO;

SELECT ENAME,DEPTNO FROM EMP ORDER BY EMPNO;

ALTER TABLE EMP ADD COLUMN Total_of_salary NUMERIC;
UPDATE EMP SET Total_of_salary=(SALARY+ IFNULL(COMMISSION,0));
ALTER TABLE EMP DROP COLUMN COMMISSION;
SELECT*FROM EMP ORDER BY EMPNO;

SELECT E.ENAME,E.SALARY FROM EMP E INNER JOIN EMP B ON E.SALARY = B.SALARY AND E.ENAME <> B.ENAME;

SELECT ENAME AS 'name',EMPNO AS 'emp_id' FROM EMP;

RENAME TABLE EMP TO EMPLOYEE;
DESCRIBE EMPLOYEE;

CREATE TABLE EMP_TAB AS SELECT * FROM EMPLOYEE;
DESCRIBE EMP_TAB;

SELECT DISTINCT E.EMPNO,E.ENAME,E.JOB,E.SALARY,E.DEPTNO,E.DATE_JOIN,E.Total_of_salary,
B.EMPNO,B.ENAME,B.JOB,B.SALARY,B.DEPTNO,B.DATE_JOIN,B.Total_of_salary
 FROM EMP_TAB E JOIN EMPLOYEE B WHERE E.EMPNO=B.EMPNO;

TRUNCATE TABLE EMPLOYEE;
SELECT * FROM EMPLOYEE;

DROP TABLE EMPLOYEE;